name = "PBouffardLocal"
uuid = "8eaab17b-0496-4753-aab0-83fd57f3786c"
repo = "git@github.com:pbouffard/JuliaPackages.git"

[packages]
d9c9bf20-ca78-4ff2-99ab-ea0dd0f9def8 = { name = "AoCElfTools", path = "A/AoCElfTools" }
